name: "build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: nixpkgs-he
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
